### ISSUE TITLE
Final Changes for Ansible 3.0 before 27.01.

### ISSUE THREAD

**Issue by resmo** [cloudscale-ch/ansible-collection-cloudscale#52]
Hi @cloudscale-ch

Please make the final changes for breaking the backwards compatibility. I'll create a the new major release (and document the steps)

**Comment by href** [comment]
I'm not aware of any backwards compatibility breaking changes, is there anything I'm missing?

In any case, we'll certailny merge the bug fix, and probably the `interfaces` feature by Tuesday. Thanks for the reminder.

**Comment by resmo** [comment]
has been addressed with 699f840fa8a532d59ed5b515c9fd442023a73dd8
